Sales truncation without AUTO_INCREMENT reset
PrestaShop/pscleaner pull request #11
Opened 2015-07-12 03:20 UTC by drzraf

When cleaning the sales TRUNCATE is used heavily and according to MySQL:
> Any AUTO_INCREMENT value is reset to its start value.
But the autoinc'ed field used by some tables may sometimes also be used as an
*absolutely* unique value by other related services.
As an example, the paybox module may use id_cart as the unique value
for the Paybox variable PBX_REF which is assumed the be unique for the whole
lifetime of the shop (or more exactly, the Paybox account).
As such, any order passed to Paybox after a cleanup would be rejected since it
would reuse an already consumed identifier.

A checkbox added to the form allows the restoration of the AUTO_INCREMENT value
for two known-to-be-sensible tables: "orders" and "cart".
In-code default is TRUE but the checkbox is unchecked by default mostly for the lack

2015-07-28 04:09 UTC, drzraf commented
ping?

2015-08-27 16:10 UTC, drzraf commented
ping !?

2015-12-23 16:03 UTC, drzraf commented
ping?

2015-12-23 20:10 UTC, Misiak4 commented
Yeah this is true, I had a lot of problems too... I have another tables marked what need to be cleaned / truncated too...because I had issues. I prefer to have it cleaned all, but for situations like you are talking about its not bad to have a checkbox...

2018-10-26 21:37 UTC, MathiasReker commented
What is status on this?

2018-11-07 18:56 UTC, eternoendless requested changes

2018-11-07 18:56 UTC, eternoendless commented on pscleaner.php
> +									'name' => $this->l('Preserve the AUTO_INCREMENT value of the two tables "orders" and "cart" from being reseted.'),
I think a better wording would be:

> Keep the AUTO_INCREMENT value of the "orders" and "cart" tables.

2018-11-07 18:56 UTC, eternoendless commented
This PR needs a rebase and a small change, but otherwise it looks good to me

2018-11-08 00:36 UTC, drzraf commented
Please do so.
(I don't use psp nor pscleaner anymore.)

2019-02-10 21:34 UTC, MathiasReker approved these changes

2019-02-10 22:14 UTC, MathiasReker commented
Rebased: https://github.com/PrestaShop/pscleaner/pull/35

2019-07-20 10:10 UTC, MathiasReker commented
@drzraf I am doing a refacto of the module. You are welcome to rebase your feature on my fork. Link to PR: https://github.com/PrestaShop/pscleaner/pull/38

2020-05-14 13:09 UTC, Progi1984 commented
Hello @drzraf , thanks for your contribution, would you mind to rebase your pull request? Thanks

2021-01-26 14:05 UTC, closed without merging